CREATE TABLE Users
(
	Id INT PRIMARY KEY IDENTITY(1,1),
	FirstName NVARCHAR(50) NOT NULL,
	LastName NVARCHAR(50) NOT NULL,
	Email NVARCHAR(100) NOT NULL,
	Username NVARCHAR(100) NOT NULL,
	PasswordHash NVARCHAR(MAX) NOT NULL,
	PasswordSalt NVARCHAR(MAX) NOT NULL,
	PhoneNumber NVARCHAR(20),
	IsActive BIT,
	CreatedAt DATETIME,
	LastLoginAt DATETIME
)

CREATE TABLE Countries(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Name NVARCHAR(100) NOT NULL
)

CREATE TABLE Cities
(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Name NVARCHAR(100) NOT NULL,
	CountryId INT NOT NULL,
	FOREIGN KEY (CountryId) REFERENCES Countries(Id)
)

CREATE TABLE Hotels
(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Name NVARCHAR(100) NOT NULL,
	Description NVARCHAR(1000),
	Address NVARCHAR(200) NOT NULL,
	CityId INT NOT NULL,
	CountryId INT NOT NULL,
	ManagerId INT NOT NULL,
	StarRating INT NOT NULL,
	IsActive BIT,
	CreatedAt DATETIME,
	FOREIGN KEY (CityId) REFERENCES Cities(Id),
	FOREIGN KEY (CountryId) REFERENCES Countries(Id),
	FOREIGN KEY (ManagerId) REFERENCES Users(Id)
)

CREATE TABLE RoomTypes
(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Name NVARCHAR(100) NOT NULL,
	Description NVARCHAR(500)
)
CREATE TABLE Rooms
(
	Id INT PRIMARY KEY IDENTITY(1,1),
	HotelId INT NOT NULL,
	RoomTypeId INT NOT NULL,
	Name NVARCHAR(50) NOT NULL,
	Capacity INT NOT NULL,
	PricePerNight DECIMAL(18,2) NOT NULL,
	IsAvailable BIT,
	Description NVARCHAR(MAX),
	FOREIGN KEY (HotelId) REFERENCES Hotels(Id),
	FOREIGN KEY (RoomTypeID) REFERENCES RoomTypes(Id)
)

CREATE TABLE RoomAvailability
(
	Id INT PRIMARY KEY IDENTITY(1,1),
	RoomId INT NOT NULL,
	Date DATETIME NOT NULL,
	Status INT NOT NULL,
	FOREIGN KEY (RoomId) REFERENCES Rooms(Id)
)

CREATE TABLE Services
(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Name NVARCHAR(100) NOT NULL,
	Description NVARCHAR(500),
	Price DECIMAL(18,2) NOT NULL,
	HotelId INT NOT NULL,
	FOREIGN KEY (HotelId) REFERENCES Hotels(Id)
)

CREATE TABLE Reservations
(
	Id INT PRIMARY KEY IDENTITY(1,1),
	UserId INT NOT NULL,
	RoomId INT NOT NULL,
	CheckInDate DATETIME NOT NULL,
	CheckOutDate DATETIME NOT NULL,
	TotalPrice DECIMAL(18,2) NOT NULL,
	Statsu NVARCHAR(50),
	CreatedAt DATETIME,
	FOREIGN KEY (UserId) REFERENCES Users(Id),
	FOREIGN KEY (RoomId) REFERENCES Rooms(Id)
)

CREATE TABLE ReservationServices
(
	Id INT PRIMARY KEY IDENTITY(1,1),
	ReservationId INT NOT NULL,
	ServiceId INT NOT NULL,
	Price DECIMAL(18,2) NOT NULL,
	FOREIGN KEY (ReservationId) REFERENCES Reservations(Id),
	FOREIGN KEY (ServiceId) REFERENCES Services(Id)
)

CREATE TABLE Reviews
(
	Id INT PRIMARY KEY IDENTITY(1,1),
	UserId INT NOT NULL,
	HotelId INT NOT NULL,
	ReservationId INT NOT NULL,
	Rating INT NOT NULL,
	Comment NVARCHAR(MAX),
	ReviewDate DATETIME,
	FOREIGN KEY (UserId) REFERENCES Users(Id),
	FOREIGN KEY (HotelId) REFERENCES Hotels(Id),
	FOREIGN KEY (ReservationId) REFERENCES Reservations(Id)
)

CREATE TABLE Notifications
(
	Id INT PRIMARY KEY IDENTITY(1,1),
	UserId INT NOT NULL,
	Title NVARCHAR(100) NOT NULL,
	Message NVARCHAR(50) NOT NULL,
	Type NVARCHAR(50) NOT NULL,
	IsRead BIT,
	SentAt DATETIME,
	FOREIGN KEY (UserId) REFERENCES Users(Id)
)

CREATE TABLE Assets
(
	Id INT PRIMARY KEY IDENTITY(1,1),
	FileName NVARCHAR(200) NOT NULL,
	Image VARBINARY(MAX),
	ImageThumb VARBINARY(MAX),
	MimeType NVARCHAR(100),
	CreatedAt DATETIME NOT NULL,
	HotelId INT NOT NULL,
	RoomId INT NOT NULL,
	FOREIGN KEY (HotelId) REFERENCES Hotels(Id),
	FOREIGN KEY (RoomId) REFERENCES Rooms(Id)
)

CREATE TABLE Roles
(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Name NVARCHAR(50) NOT NULL
)

CREATE TABLE UserRoles
(
	UserId INT NOT NULL, 
	RoleId INT NOT NULL,
	PRIMARY KEY(UserId, RoleId),
	FOREIGN KEY (UserId) REFERENCES Users(Id),
	FOREIGN KEY (RoleId) REFERENCES Roles(Id)
)

CREATE TABLE Payment
(
	Id INT PRIMARY KEY IDENTITY(1,1),
	ReservationId INT NOT NULL,
	Provider NVARCHAR(50) NOT NULL DEFAULT N'stripe',
	ProviderPaymentId NVARCHAR(200) NOT NULL,
	Amount DECIMAL(18,2) NOT NULL, 
	Currency NVARCHAR(10) NOT NULL DEFAULT N'USD',
	Status NVARCHAR(50) NOT NULL DEFAULT N'processing',
	CreatedAt DATETIME NOT NULL,
	UpdatedAt DATETIME NULL,
	IsDeleted BIT NULL,
	DeletedTime DATETIME NULL,
	FOREIGN KEY (ReservationId) REFERENCES Reservations(Id)

)